import type { Config } from "tailwindcss";

/** Maps directly to CSS vars in globals.css so tokens stay the single source of truth. */
const config: Config = {
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        paper:      "var(--color-paper)",
        "paper-hi": "var(--color-paper-hi)",
        "paper-sunk":"var(--color-paper-sunk)",
        ink:        "var(--color-ink)",
        "ink-2":    "var(--color-ink-2)",
        "ink-3":    "var(--color-ink-3)",
        "ink-4":    "var(--color-ink-4)",
        rule:       "var(--color-rule)",
        "rule-soft":"var(--color-rule-soft)",
        "rule-card":"var(--color-rule-card)",
        brand:      "var(--color-brand)",
        "brand-hover":"var(--color-brand-hover)",
        "brand-press":"var(--color-brand-press)",
        "brand-tint":"var(--color-brand-tint)",
        success:    "var(--color-success)",
        "success-tint":"var(--color-success-tint)",
        "success-ink":"var(--color-success-ink)",
        info:       "var(--color-info)",
        "info-tint":"var(--color-info-tint)",
        "info-ink": "var(--color-info-ink)",
        warn:       "var(--color-warn)",
        "warn-tint":"var(--color-warn-tint)",
        "warn-ink": "var(--color-warn-ink)",
        danger:     "var(--color-danger)",
        "danger-tint":"var(--color-danger-tint)",
        "danger-ink":"var(--color-danger-ink)",
      },
      fontFamily: {
        sans:     ["var(--font-sans)"],
        wenkai:   ["var(--font-wenkai)"],
        mono:     ["var(--font-mono)"],
        num:      ["var(--font-num)"],
        mashan:   ["'Ma Shan Zheng'", "serif"],
        serifsc:  ["'Noto Serif SC'", "serif"],
      },
      fontSize: {
        display: ["var(--fs-display)", { lineHeight: "var(--lh-display)" }],
        h1:      ["var(--fs-h1)",      { lineHeight: "var(--lh-h1)" }],
        h2:      ["var(--fs-h2)",      { lineHeight: "var(--lh-h2)" }],
        h3:      ["var(--fs-h3)",      { lineHeight: "var(--lh-h3)" }],
        h4:      ["var(--fs-h4)",      { lineHeight: "var(--lh-h4)" }],
        body:    ["var(--fs-body)",    { lineHeight: "var(--lh-body)" }],
        "body-sm":["var(--fs-body-sm)",{ lineHeight: "var(--lh-body-sm)" }],
        meta:    ["var(--fs-meta)",    { lineHeight: "var(--lh-meta)" }],
        micro:   ["var(--fs-micro)",   { lineHeight: "var(--lh-micro)" }],
      },
      borderRadius: {
        xs:   "var(--radius-xs)",
        sm:   "var(--radius-sm)",
        md:   "var(--radius-md)",
        lg:   "var(--radius-lg)",
        xl:   "var(--radius-xl)",
        pill: "var(--radius-pill)",
      },
      boxShadow: {
        xs: "var(--shadow-xs)", sm: "var(--shadow-sm)",
        md: "var(--shadow-md)", lg: "var(--shadow-lg)",
        xl: "var(--shadow-xl)", focus: "var(--shadow-focus)",
      },
      spacing: {
        1:"var(--sp-1)",2:"var(--sp-2)",3:"var(--sp-3)",4:"var(--sp-4)",
        5:"var(--sp-5)",6:"var(--sp-6)",7:"var(--sp-7)",8:"var(--sp-8)",
        9:"var(--sp-9)",10:"var(--sp-10)",11:"var(--sp-11)",12:"var(--sp-12)",
      },
    },
    screens: { sm: "641px", md: "961px", lg: "1281px" },
  },
  plugins: [],
};
export default config;
